function out1 = Hess0(p0,p1,lambda,x,y,zz)
%HESS0
%    OUT1 = HESS0(P0,P1,LAMBDA,X,Y,ZZ)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    13-Nov-2017 18:23:59

t2 = exp(p0);
t3 = t2+1.0;
t4 = p0.*2.0;
t5 = exp(t4);
t6 = 1.0./t3;
t7 = y-1.0;
t8 = t6-1.0;
t9 = 1.0./t3.^2;
t10 = 1.0./t8;
out1 = [t2.*t6.*y-t5.*t9.*y-t2.*t7.*t9.*t10+1.0./t3.^3.*t5.*t7.*t10.*2.0-1.0./t3.^4.*t5.*t7.*1.0./t8.^2,zz,zz,zz,zz,zz,zz,zz,zz];
