function J = Jac(p0,p1,lambda,x,y,zz)
%JAC
%    J = JAC(P0,P1,LAMBDA,X,Y,ZZ)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    13-Nov-2017 18:23:57

t2 = exp(p0);
t3 = 1.0./lambda;
t9 = t3.*x;
t4 = exp(-t9);
t5 = t2+1.0;
t6 = exp(p1);
t7 = t6+1.0;
t8 = 1.0./t7;
t10 = 1.0./t5.^2;
t11 = 1.0./t5;
t12 = t8-t11;
t13 = t4.*t12;
t14 = t8-t13;
t15 = 1.0./t14;
t16 = 1.0./t7.^2;
t17 = y-1.0;
t18 = t6.*t16;
t19 = t18-t4.*t6.*t16;
t20 = -t8+t13+1.0;
t21 = 1.0./t20;
t22 = -t8+t11;
t23 = 1.0./lambda.^2;
t24 = t4.*t22;
J = [t2.*t4.*t10.*t17.*t21+t2.*t4.*t10.*t15.*y,t17.*t19.*t21+t15.*t19.*y,(t4.*t17.*t22.*t23.*x)./(t8+t24-1.0)-(t4.*t22.*t23.*x.*y)./(t8+t24)];
